// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgj8ryGXk2buSusbBc2K6iPFWd3X3OCY4',
    appId: '1:534736508777:web:5e987d8711c17336b1cff8',
    messagingSenderId: '534736508777',
    projectId: 'safespace-app-c6bfd',
    authDomain: 'safespace-app-c6bfd.firebaseapp.com',
    storageBucket: 'safespace-app-c6bfd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBLyxULAoEtSU6aKnasH6kd4N_RDhdNM',
    appId: '1:534736508777:android:a28074e8b2e5cd71b1cff8',
    messagingSenderId: '534736508777',
    projectId: 'safespace-app-c6bfd',
    storageBucket: 'safespace-app-c6bfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwHlbU7-0l7Fchqn9l6u-V6WpdDVNjMps',
    appId: '1:534736508777:ios:8b8ddfbbd4a7b526b1cff8',
    messagingSenderId: '534736508777',
    projectId: 'safespace-app-c6bfd',
    storageBucket: 'safespace-app-c6bfd.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiBk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwHlbU7-0l7Fchqn9l6u-V6WpdDVNjMps',
    appId: '1:534736508777:ios:8b8ddfbbd4a7b526b1cff8',
    messagingSenderId: '534736508777',
    projectId: 'safespace-app-c6bfd',
    storageBucket: 'safespace-app-c6bfd.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiBk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgj8ryGXk2buSusbBc2K6iPFWd3X3OCY4',
    appId: '1:534736508777:web:43cd0b94630a2e7cb1cff8',
    messagingSenderId: '534736508777',
    projectId: 'safespace-app-c6bfd',
    authDomain: 'safespace-app-c6bfd.firebaseapp.com',
    storageBucket: 'safespace-app-c6bfd.firebasestorage.app',
  );
}
